### ISSUE TITLE
Recent change breaks some JIRA URLs

### ISSUE THREAD

**Issue by eserte** [gnustavo/JIRA-Client#1]
The change 7b744740c63d19f277c824ee48877127ad8ea478 breaks if JIRA URLs with a path component not equal "/" are used. For example, our JIRA URL looks like this: https://extranet.example.com/jira (real domain name mangled).

I don't exactly understand what this commit should fix. Maybe it should be instead checked if a URL containing the rpc path is already supplied? So the check should go like this:

```
if ($url->path_query() ne '/rpc/soap/jirasoapservice-v2?wsdl') {
```

?

Regards, Slaven

**Comment by gnustavo** [comment]
Ugh. You're rigth. I haven't thought about the possibility of having an extra component in the URL path, as yours have "/jira". This breaks the assumptions I've used in the code.

Before that commit JIRA::Client::new assumed its second argument was the JIRA server "base" URL, to which it would append the default WSDL descriptor path "/rpc/soap/jirasoapservice-v2?wsdl".

The purpose of that commit was to enable people to use JIRA::Client with non-standard WSDL descriptors. I tried to do that by checking if the URL already contained a path. But, as you just showed to me, it's possible for the "base" URL to have a path component.

I'm thinking about how to fix this check. Perhaps I should simply see if the URL contains the substring "?wsdl", as it seems to me that even with non-standard WSDL descriptors, they would contain this. This would be simple to do and keep compatibility with the past.

Another approach would be to require an explicit signal to show that the URL is complete and not "base". I could require, for example, that it should be passed as an array-ref containing the URL as a single element. But it seems ugly.

Hmmm... what do you think? I'm willing to try the first approach of checking for "?wsdl" in the URL.

**Comment by eserte** [comment]
Maybe it's better to be explicit. First, you could switch the constructor to use named parameters (and keep the current three-argument call for backward compatibility and for quick usage). Then it's easy to make a distinction between "baseurl" and "wsdlurl" (probably you should choose better names), e.g.:

```
  my $jira = JIRA::Client->new({ baseurl => 'http://jira.example.com/jira',
                                 # or alternatively wsdlurl => 'http://jira.example.com/jira/rpc/...?wsdl',
                                 user => 'user',
                                 password =>  'passwd',
                              });
```

Defining both baseurl and wsdlurl should probably be an error.

**Comment by gnustavo** [comment]
Good idea. I've just implemented it and make a new release 0.39.

Thank you!

**Comment by eserte** [comment]
Still does not look right for me. These two lines:

```
my $url = URI->new($args->{baseurl});
$url->path_query($args->{wsdl});
```

mean that I have to specify baseurl=http://extranet.example.com
and wsdl=/jira/rpc/soap/jirasoapservice-v2?wsdl in our case, but
this is not correct --- the baseurl is
http://extranet.example.com/jira here, and the wsdl appendix is a
standard one, so does not need to be specified.

I would suggest to just append wsdl to the baseurl without using
URI.pm and path_query at all. There's just double slash cleanup
here, in case somebody specifies baseurl with a trailing slash.

See my pull request.

**Comment by gnustavo** [comment]
2012/8/1 Slaven Rezić <
reply@reply.github.com

> Still does not look right for me. These two lines:
> 
> ```
> my $url = URI->new($args->{baseurl});
> $url->path_query($args->{wsdl});
> ```
> 
> mean that I have to specify baseurl=http://extranet.example.com
> and wsdl=/jira/rpc/soap/jirasoapservice-v2?wsdl in our case, but
> this is not correct --- the baseurl is
> http://extranet.example.com/jira here, and the wsdl appendix is a
> standard one, so does not need to be specified.
> 
> I would suggest to just append wsdl to the baseurl without using
> URI.pm and path_query at all. There's just double slash cleanup
> here, in case somebody specifies baseurl with a trailing slash.
> 
> See my pull request.

You're right. I just applied your commit and released v0.40. Thank you.

## 

Gustavo.
